### ISSUE TITLE
All-Items view in survival

### ISSUE THREAD

**Issue by bell07** [bell07/minetest-smart_inventory#2]
At the time there is no way to show all ( or all revealed) items. An additional items mode needs to be implemented.
Technically I just need to remove the limitation "min 3 chars for search" to allow searching without restriction to get the list. Maybe an additional parameter to enable/disable this new mode because the list does show not revealed but crafteable Items too ...

**Comment by Gerold55** [comment]
You should be able to add and take away the mods (items) you view from the list but they are technically still there ;)

**Comment by bell07** [comment]
All items are technically allways still there. The initial idea was just to show the relevant items to the survival player. In other words only craftable items. At the first crafteable by items in inventory.
In the next the "doc" mod was introduced, I like the concept for "Revealed/not revealed" items in doc mod. The search functionality is able to show not revealed items, but craftable by. Therefore I added an restriction to minimum 3 characters needs to be entered, so you need to know which non revealed item you look for. The "show all items" requirement undermines this concept.

Hm, if doc items is used there is no restriction for 3 characters but the new button respect the revealed state. For example:

New game, at the first the "wood" is revealed, and in the second step the "stick".
The default view and the search does show the wood axe. The wood axe is not revealed but can be crafted by already revealed items wood and stick.

In the search field you can find the wood axe by search for "wood" or "axe" 
The new "show all" item is not able to show the wood axe because of not revealed. Of course the wood and stick are displayed.

Of course in case no doc mod installed all items are shown like in creative page.

**Comment by Gerold55** [comment]
So you have to figure out how to make it so all items are displayed even if you don't have that item materials?

**Comment by bell07** [comment]
Implemented as proposed
