### ISSUE TITLE
Auto-Crafting support

### ISSUE THREAD

**Issue by bell07** [bell07/minetest-smart_inventory#3]
The crafting view should more support the crafting. The simplest way is to auto-move items to crafting grid as shown in crafting preview

**Comment by Gerold55** [comment]
You would also have to add button so it auto-moves items and if you don't have items it refuses to do so :)

**Comment by bell07** [comment]
Yes. The "Survival Experience" should not be broken.If you do not have an required item that no item appears.
It should not be an issue to move items if the recipe is incomplete because the "move back" button already exists

**Comment by bell07** [comment]
Implemented but the button texture still missed

**Comment by bell07** [comment]
Done in 1befdf7abfd69071dc50cfe3b80e28b33b923959. Thanks again to Stix
